axes = {
    "AEV": {"bins": 100, "label": r"Artificial variable $V$", "leg": r"$V$"},
    "AEV0": {"bins": 100, "label": r"$V$", "leg": r"$V$"},
    "AEV1": {"bins": 100, "label": r"$V_{m_{\widetilde{\mathrm{t}}} < 1000\,\mathrm{GeV}}$", "leg": r"$V_{m_{\widetilde{\mathrm{t}}} < 1000\,\mathrm{GeV}}$"},
    "AEV2": {"bins": 100, "label": r"$V_{m_{\widetilde{\mathrm{t}}} > 500\,\mathrm{GeV}}$", "leg": r"$V_{m_{\widetilde{\mathrm{t}}} > 500\,\mathrm{GeV}}$"},
    "mStop": {"bins": 6, "lims": (500, 1000), "label": r"$m_{\widetilde{\mathrm{t}}}$ [GeV]", "leg": r"$m_{\widetilde{\mathrm{t}}}$", "unit": "GeV"},
    "dR_M": {"bins": 100, "lims": (250, 2000), "label": r"$M_{\Delta R}$ [GeV]", "leg": r"$M_{\Delta R}$"},
    "pair_M_avg": {"bins": 100, "lims": (250, 2000), "label": r"$M_{\mathrm{pred}}^{\mathrm{avg}}$ [GeV]", "leg": r"$M_{\mathrm{pred}}^{\mathrm{avg}}$"},
    "Truth_M_high": {"bins": 100, "lims": (250, 2000), "label": r"$M_{\mathrm{truth}}^{\mathrm{high}}$ [GeV]", "leg": r"$M_{\mathrm{truth}}^{\mathrm{high}}$"},
    "Truth_M_low": {"bins": 100, "lims": (250, 2000), "label": r"$M_{\mathrm{truth}}^{\mathrm{low}}$ [GeV]", "leg": r"$M_{\mathrm{truth}}^{\mathrm{low}}$"},
    "Truth_M_avg": {"bins": 100, "lims": (250, 2000), "label": r"$M_{\mathrm{truth}}^{\mathrm{avg}}$ [GeV]", "leg": r"$M_{\mathrm{truth}}^{\mathrm{avg}}$"},
    "Truth_high_M_high": {"bins": 100, "lims": (250, 2000), "label": r"$M_{\mathrm{truth(high)}}^{\mathrm{high}}$ [GeV]", "leg": r"$M_{\mathrm{truth(high)}}^{\mathrm{high}}$"},
    "Truth_high_M_low": {"bins": 100, "lims": (250, 2000), "label": r"$M_{\mathrm{truth(high)}}^{\mathrm{low}}$ [GeV]", "leg": r"$M_{\mathrm{truth(high)}}^{\mathrm{low}}$"},
    "Truth_high_M_avg": {"bins": 100, "lims": (250, 2000), "label": r"$M_{\mathrm{truth(high)}}^{\mathrm{avg}}$ [GeV]", "leg": r"$M_{\mathrm{truth(high)}}^{\mathrm{avg}}$"},
    "Truth_avg_M_high": {"bins": 100, "lims": (250, 2000), "label": r"$M_{\mathrm{truth(avg)}}^{\mathrm{high}}$ [GeV]", "leg": r"$M_{\mathrm{truth(avg)}}^{\mathrm{high}}$"},
    "Truth_avg_M_low": {"bins": 100, "lims": (250, 2000), "label": r"$M_{\mathrm{truth(avg)}}^{\mathrm{low}}$ [GeV]", "leg": r"$M_{\mathrm{truth(avg)}}^{\mathrm{low}}$"},
    "Truth_avg_M_avg": {"bins": 100, "lims": (250, 2000), "label": r"$M_{\mathrm{truth(avg)}}^{\mathrm{avg}}$ [GeV]", "leg": r"$M_{\mathrm{truth(avg)}}^{\mathrm{avg}}$"},
    "Mjj_msortedP1_high": {"bins": 100, "lims": (250, 2000), "label": r"$M_{1}^{\mathrm{high}}$ [GeV]", "leg": r"$M_{1}^{\mathrm{high}}$"},
    "Mjj_msortedP1_low": {"bins": 100, "lims": (250, 2000), "label": r"$M_{1}^{\mathrm{low}}$ [GeV]", "leg": r"$M_{1}^{\mathrm{low}}$"},
    "Mjj_msortedP2_high": {"bins": 100, "lims": (250, 2000), "label": r"$M_{2}^{\mathrm{high}}$ [GeV]", "leg": r"$M_{2}^{\mathrm{high}}$"},
    "Mjj_msortedP2_low": {"bins": 100, "lims": (250, 2000), "label": r"$M_{2}^{\mathrm{low}}$ [GeV]", "leg": r"$M_{2}^{\mathrm{low}}$"},
    "Mjj_msortedP3_high": {"bins": 100, "lims": (250, 2000), "label": r"$M_{3}^{\mathrm{high}}$ [GeV]", "leg": r"$M_{3}^{\mathrm{high}}$"},
    "Mjj_msortedP3_low": {"bins": 100, "lims": (250, 2000), "label": r"$M_{3}^{\mathrm{low}}$ [GeV]", "leg": r"$M_{3}^{\mathrm{low}}$"},
}
